version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres
    restart: always

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/storagedb"
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always

  test:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      TEST_DATABASE_URL: "postgresql://postgres:123456@db:5432/test_storagedb"
    command: pytest
    restart: on-failure

volumes:
  pgdata:
