services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_storagedb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/storagedb"
      TEST_DATABASE_URL: "postgresql://postgres:123456@db:5432/test_storagedb"
    ports:
      - "8000:8000"

  test:
    build: .
    depends_on:
      - db
    environment:
      TEST_DATABASE_URL: "postgresql://postgres:123456@db:5432/test_storagedb"
    command: pytest
